<%@include file="/WEB-INF/protected-jsp/commons/common.jsp" %>

<v:hidden property="id"/>
<table>
	<tr>
		<td>
		<v:text
			labelKey="label.sitra.core.Sistema.crud.nome"
			property="nome"
			size="60"
			maxlength="200"
			required="true"
			validateType="STRING"
			validateMinLength="3"
			validateMaxLength="200"
		/>
		</td>
		<td>
		<v:text
			labelKey="label.sitra.core.Sistema.crud.sigla"
			property="sigla"
			size="20"
			maxlength="20"
			required="true"
			validateType="STRING"
			validateMinLength="3"
			validateMaxLength="20"
		/>
		</td>
	</tr>
	<tr>
		<td colspan="2">
		<v:text
			labelKey="label.sitra.core.Sistema.crud.gerencia"
			property="gerencia"
			size="60"
			maxlength="200"
			required="true"
		/>
		</td>
	</tr>
	<tr>
		<td>
		<v:text
			labelKey="label.sitra.core.Sistema.crud.analistaResponsavel"
			property="analistaResponsavel"
			size="60"
			maxlength="200"
			required="true"
		/>
		</td>
		<td>
		<v:text
			labelKey="label.sitra.core.Sistema.crud.ramal"
			property="ramal"
			size="20"
			maxlength="20"
			required="true"
		/>
		</td>
	</tr>
	<tr>
		<td>
		<v:text
			labelKey="label.sitra.core.Sistema.crud.ownerHomologacao"
			property="ownerHomologacao"
			size="20"
			maxlength="20"
			required="true"
		/>
		</td>
		<td>
		<v:text
			labelKey="label.sitra.core.Sistema.crud.dblinkHomologacao"
			property="dblinkHomologacao"
			size="50"
			maxlength="100"
			required="true"
		/>
		</td>
	</tr>
	<tr>
		<td>
		<v:text
			labelKey="label.sitra.core.Sistema.crud.ownerProducao"
			property="ownerProducao"
			size="20"
			maxlength="20"
			required="true"
		/>
		</td>
		<td>
		<v:text
			labelKey="label.sitra.core.Sistema.crud.dblinkProducao"
			property="dblinkProducao"
			size="50"
			maxlength="100"
			required="true"
		/>
		</td>
	</tr>
	<tr>
		<td colspan="2">
		<v:text
			labelKey="label.sitra.core.Sistema.crud.dblinkDesenvolvimento"
			property="dblinkDesenvolvimento"
			size="50"
			maxlength="100"
			required="true"
		/>
		</td>
	</tr>
</table>